// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackEvent.WebApi.Infrastructure.Data;

#nullable disable

namespace TrackEvent.WebApi.Migrations
{
    [DbContext(typeof(TrackEventDbContext))]
    partial class TrackEventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackEvent.WebApi.Domain.Entities.UserEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("anonymous_id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_version");

                    b.Property<string>("Browser")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("browser");

                    b.Property<string>("BrowserVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("browser_version");

                    b.Property<string>("BuildNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_number");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_id");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_type");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("Experiments")
                        .HasColumnType("jsonb")
                        .HasColumnName("experiments");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("feature_id");

                    b.Property<string>("FeatureName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("feature_name");

                    b.Property<string>("FeatureType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_type");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NetworkType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("network_type");

                    b.Property<string>("Os")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("os");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("os_version");

                    b.Property<string>("PageName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("page_name");

                    b.Property<string>("PageUrl")
                        .HasColumnType("text")
                        .HasColumnName("page_url");

                    b.Property<string>("PreviousPageName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("previous_page_name");

                    b.Property<string>("PreviousPageUrl")
                        .HasColumnType("text")
                        .HasColumnName("previous_page_url");

                    b.Property<string>("PreviousScreenName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("previous_screen_name");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ScreenName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("screen_name");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventTime")
                        .HasDatabaseName("idx_user_events_event_time");

                    b.HasIndex("FeatureId", "EventTime")
                        .HasDatabaseName("idx_user_events_feature_time");

                    b.HasIndex("Source", "EventTime")
                        .HasDatabaseName("idx_user_events_source_time");

                    b.HasIndex("UserId", "EventTime")
                        .HasDatabaseName("idx_user_events_user_time");

                    b.HasIndex("ClientId", "SessionId", "EventTime")
                        .HasDatabaseName("idx_user_events_client_session_time");

                    b.ToTable("user_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
